Description: S3 Bucket for GIC Data Access

Parameters:
  InstitutionName:
    Type: String
    Description: The short name of your institution. bhc, chop (lowercase!)
    Default: prototype
  ServiceWorkbenchAccount:
    Type: String
    Description: The AWS account ID of your service workbench account
    Default: 302142166944
  ExternalId:
    Type: String
    Description: A unique ID used to identify this account
    Default: 12345

Resources:
#-------------------------------------------------------------------------------
#                               Users & Access Keys
#-------------------------------------------------------------------------------
  DataUploadUser:
    Type: AWS::IAM::User
    Properties:
      Path: "/data-upload-user/"
      
  DataUploadUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref DataUploadUser
    
  DataUploadUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ['-', [!Ref InstitutionName, data-upload-user-secret]]
      Description: Access Key secret for Data Upload User
      SecretString: !GetAtt DataUploadUserAccessKey.SecretAccessKey

#-------------------------------------------------------------------------------
#                                      Roles
#-------------------------------------------------------------------------------
  # Uploaders need PUT access to the S3 bucket, but nothing else
  # Each institution has a single uploader, tied to their PIC-SURE node
  DataUploader:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PicSureDataUploadRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Join ['', ['arn:aws:iam::302142166944:user/data-upload-user/', !Ref DataUploadUser]]
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: PicSureDataUploadPolicy 
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - 'arn:aws:s3:::pic-sure-data-sharing-bucketprototype'
                  - 'arn:aws:s3:::pic-sure-data-sharing-bucketprototype*'
                  - 'arn:aws:s3:::pic-sure-data-sharing-bucketprototype/*'
                # Condition:
                #   StringEquals:
                #     sts:ExternalId: !Ref ExternalId

  
