Description: S3 Bucket for GIC Data Access

Parameters:
  InstitutionName:
    Type: String
    Description: The short name of your institution. bhc, chop (lowercase!)
    Default: prototype
  ServiceWorkbenchAccount:
    Type: String
    Description: The AWS account ID of your service workbench account
    Default: 302142166944

Resources:
#-------------------------------------------------------------------------------
#                               Users & Access Keys
#-------------------------------------------------------------------------------
  DataUploadUser:
  # make dep on policy
    Type: AWS::IAM::User
    Properties:
      Path: "/data-upload-user/"
      
  DataUploadUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref DataUploadUser
    
  DataUploadUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ['-', [!Ref InstitutionName, data-upload-user-secret]]
      Description: Access Key secret for Data Upload User
      SecretString: !GetAtt DataUploadUserAccessKey.SecretAccessKey
#-------------------------------------------------------------------------------
#                                Roles & Policies
#-------------------------------------------------------------------------------
  PicSureDataUploadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Users:
        - !Ref DataUploadUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject*
              - s3:DeleteObject*
            Resource:
              - 'arn:aws:s3:::pic-sure-data-sharing-bucketprototype/*' 
            # Condition:
            #   StringEquals:
            #     sts:ExternalId: !Ref ExternalId
    
  # Uploaders need PUT access to the S3 bucket, but nothing else
  # Each institution has a single uploader, tied to their PIC-SURE node
  DataUploader:
    DependsOn: PicSureDataUploadPolicy
    Type: AWS::IAM::Role
    Properties:
      RoleName: PicSureDataUploadRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS:
              - '302142166944'
              - !Sub 'arn:aws:iam::302142166944:user/data-upload-user/${DataUploadUser}'
            Action:
              - 'sts:AssumeRole'
      Policies: []
