Description: S3 Bucket for GIC Data Access

Parameters:
  InstitutionName:
    Type: String
    Description: The short name of your institution. bhc, chop (lowercase!)
    Default: prototype
  ServiceWorkbenchAccount:
    Type: String
    Description: The AWS account ID of your service workbench account
    Default: 555035503484
  ThirdPartyUploadUsers:
    Type: List<String>
    Description: The AWS iam IDs for the 3rd party users that will upload data
    Default: 'arn:aws:iam::302142166944:user/data-upload-user/frank-DataUploadUser-WKWGL8C9VUBK'
Resources:
#-------------------------------------------------------------------------------
#                               Users & Access Keys
#-------------------------------------------------------------------------------
  DataUploadUser:
  # make dep on policy
    Type: AWS::IAM::User
    Properties:
      Path: "/data-upload-user/"
      
  DataUploadUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref DataUploadUser
    
  DataUploadUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ['-', [!Ref InstitutionName, data-upload-user-secret]]
      Description: Access Key secret for Data Upload User
      SecretString: !GetAtt DataUploadUserAccessKey.SecretAccessKey
#-------------------------------------------------------------------------------
#                                Roles & Policies
#-------------------------------------------------------------------------------
  # Define what we want upload users (PIC-SUREs) to be able to do.
  PicSureDataUploadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref DataUploader
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject*
              - s3:DeleteObject*
            Resource:
              - 'arn:aws:s3:::pic-sure-data-sharing-bucketprototype/*' 
  # This role is attached to the PicSureDataUploadPolicy in that policy
  # All this role does is specify who can assume the role. What the role allows
  # is specified in the policy, and what users _have_ assumed the role is
  # determined at runtime, and with a 12 hour expiry
  DataUploader:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PicSureDataUploadRole
      # unit = seconds. 12 hours
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
          # This is messy, but this is how you append to an array in CFT land:
          # 1) Join the original array
          # 2) Join that string and the value you want to append, using the
          # same delimiter
          # 3) Split that string on the shared delimiter 
            Principal:
              AWS: !Split [',', !Join [',', [!Join [',', !Ref ThirdPartyUploadUsers], !Ref ServiceWorkbenchAccount, !Sub 'arn:aws:iam::${ServiceWorkbenchAccount}:user/data-upload-user/${DataUploadUser}']]]
            Action:
              - 'sts:AssumeRole'
      Policies: []

  # The site owner runs a Service Workbench instance that needs
  # Fairly universal access to the S3 bucket
  SWBClient:
    Type: AWS::IAM::Role
    Properties:
      # unit seconds. 12 hours
      MaxSessionDuration: 43200
      RoleName: SWBDataConsumerRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Ref ServiceWorkbenchAccount
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: PicSureDataUploadPolicy 
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource:
                  - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName, '/*']]
                  - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName]]
                Action:
                  - s3:*

#-------------------------------------------------------------------------------
#                                Buckets & Policies
#-------------------------------------------------------------------------------
  # We need a bucket for study data
  StudyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', ['pic-sure-data-sharing-bucket', !Ref InstitutionName]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  # In addition to roles, buckets have policies. Policies list roles, but also
  # fracture permissions by dictating some permissions directly, like allowed
  # protocols. We use this policy to link our roles to the bucket, as well
  # as to enforce encryption both on bucket and en route
  StudyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - DataUploader
      - SWBClient
    Properties:
      Bucket: !Join ['', ['pic-sure-data-sharing-bucket', !Ref InstitutionName]]
      PolicyDocument:
        Statement:
          # TODO: Once I have kms key, restrict here
          - Sid: Deny requests that do not use TLS/HTTPS
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName, '/*']]
              - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName]]
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: Allow PIC-SURE clients with uploader role
            Effect: Allow
            Principal:
              AWS: 
              - !Sub 'arn:aws:iam::${ServiceWorkbenchAccount}:role/PicSureDataUploadRole'
              - arn:aws:iam::302142166944:role/PicSureDataUploadRole
            Action:
              - s3:PutObject*
              - s3:DeleteObject*
            Resource:
              - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName, '/*']]
              - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName]]
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: Allow SWB clients with everything role
            Effect: Allow
            Principal:
              AWS: 
              - !Sub arn:aws:iam::${ServiceWorkbenchAccount}:role/SWBDataConsumerRole
            Action: s3:* #TODO: narrow permissions
            Resource:
              - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName, '/*']]
              - !Join ['', ['arn:aws:s3:::pic-sure-data-sharing-bucket', !Ref InstitutionName]]
            Condition:
              Bool:
                aws:SecureTransport: false
